### ISSUE TITLE
Might be vulnerable to file rename attacks

### ISSUE THREAD

**Issue by alexanderkjall** [FiloSottile/passage#2]
This is very hypothetical, and only based on me reading the source code since I had a bit of trouble installing it.

But pass is vulnerable to file rename attacks, if an attacker have control over the encrypted files then he can copy one file into another, and cause the teams password for service A to be leaked to service B.

See CVE-2020-28086 ( https://blog.hackeriet.no/filename-rename-in-pass/ ) for my writeup on the issue.

It looks like there isn't any protection in passage for this type of attack either.

Sorry if I was wrong about this, just close this issue then :)

And this isn't really responsible disclosure, but i reckon that since this is so new there isn't any user impact to take into account.

**Comment by FiloSottile** [comment]
pass has a concept of verifying signatures to defend against an active attacker, but I removed that from passage (partly because it felt just partial, as your issue shows). passage makes no attempt at integrity against an attacker that can modify the storage, so this is outside the threat model.

(It would be nice to introduce strong binding, but I would want it wired all the way into the age plugins, so that for example you can see the password being decrypted on a touch bar or hardware token screen. https://github.com/romanz/trezor-agent/pull/374#issuecomment-990178742)
